### PR TITLE
Add Eclipse files to gitignore

### PR DESCRIPTION
**Pull request by vic-cw**

### CODE REVIEW

**Comment by vic-cw** [comment]
@evanchooly just a friendly reminder that this and other pull requests are awaiting your approval

**Comment by evanchooly** [comment]
gah!  you're right!  I'll take a look in the morning.

**Comment by evanchooly** [comment]
all merged!  and I pushed a release.  should be up soon.  0.8 is the version.

**Comment by vic-cw** [comment]
This is great !!

**Pull request merged**
